exclude:
  - aws-eks-no-public-cluster-access
  - aws-eks-no-public-cluster-access-to-cidr
  - aws-s3-block-public-acls
  - aws-s3-block-public-policy
  - aws-s3-ignore-public-acls
  - aws-s3-no-public-buckets
  - aws-s3-encryption-customer-key
  - aws-cloudfront-enable-waf
  - aws-ecr-enforce-immutable-repository
  - aws-cloudfront-use-secure-tls-policy
  - aws-eks-encrypt-secrets
  - aws-ec2-no-public-egress-sgr
  - aws-iam-no-policy-wildcards
  - aws-s3-no-public-buckets
